### ISSUE TITLE
`incl_lines` parameter is ignored for SED computation

### ISSUE THREAD

**Issue by smaret** [dullemond/radmc3d-2.0#11]
I've set up a model that includes lines (I have a `lines.inp` file in my model directory). When I compute the SED, I get the following message:

```console
% radmc3d sed
 ERROR: Cannot make SED with line mode on.
```

I've tried to set `incl_lines = 0` parameter in the `radmc3d.inp` file but I still get the error. So it seems that this parameter is ignored for the SED computation. Is this a bug?

The SED computation works fine if I remove the `lines.inp` file.

**Comment by dullemond** [comment]
Sorry, I forgot to answer. Indeed, if lines.inp is in the directory, RADMC-3D will automatically switch on the lines mode. Once the lines mode is on, it is indeed impossible to make the SED computation. I did that because in the past people made SEDs and wondered where the lines were. 

Indeed, setting `incl_lines=0` in the `radmc3d.inp` does not switch the lines off. That is a bug. I have now moved the SED vs lines check until after the reading of the radmc3d.inp file. That should then allow you to set `incl_lines = 0` in the radmc3d.inp file and switch off the lines. Committed and pushed.

Note that you can also switch the lines off by adding `noline` in the command line.
